# Workflow for OWASP Baseline scan

name: SEC488 DAST

# Controls when the action will run.  Triggers the workflow on push or pull request
# events but only for the master branch

on:
  push:
    branches:  [ master ]
  pull:
    branches:  [ master ]
    
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job run on
    runs-on:  ubuntu-lastest
    
    steps:
    
    - uses: actions/checkout@v2
    
    - name: Startup web server
      run: docker run -v $(pwd) :/var/www/html -dit --rm php php:apache
      
    - name: OWASP Scan and create Issue of results
      uses: zaproxy/action-baseline@v0.3.0
      with:
      target:  http://172.17.0.2
